version: '3.8'
services:
  frr:
    image: frrouting/frr:v7.4.0
    network_mode: host
    privileged: true
    volumes:
    - ./:/etc/frr/
  crs:
    image: networkop/cloudroutesync
    network_mode: host
    privileged: true
    command: ["-cloud", "${CLOUD}"]